import { Console } from 'console'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [valueL, setValueL] = useState(1);
  const [valueP, setValueP] = useState(1);
  const [valueS, setValueS] = useState(1);
  const [valueV, setValueV] = useState(1);
  const [result, setResult] = useState(0)

  const updateInput = (e:  { target: HTMLInputElement }, setfunc: Function) => {
    setfunc(e.target.value)
  };
  console.log(valueP)

  const calculate = () => {
    setResult((valueL * valueP * valueS * (valueV ** 2)) / 2);
    console.log(result)
  } 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <h2>Taşıma Kuvveti</h2>
        <span>Cl : taşıma katsayı</span><input onChange={(e) => updateInput(e, setValueL)} type="number" name="" id=""  value={valueL}  />
        <span>ρ∞: hava yoğunluğu</span><input onChange={(e) => updateInput(e, setValueP)} type="number" name="" id=""  value={valueP}/>
        <span>S: Kanat Alanı</span><input onChange={(e) => updateInput(e, setValueS)} type="number" name="" id=""  value={valueS}/>
        <span>V: Hava hızı</span><input onChange={(e) => updateInput(e, setValueV)} type="number" name="" id=""  value={valueV}/>
        <button onClick={() => calculate()}>hesapla</button>
        <p>{result}</p>
      </main>

      
    </div>
  )
}

export default Home
